
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action FileAction;

	private global::Gtk.Action HelpAction;

	private global::Gtk.Action quitAction;

	private global::Gtk.Action aboutAction;

	private global::Gtk.VBox vbox1;

	private global::Gtk.MenuBar menubar1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.HPaned hpaned1;

	private global::Gtk.VBox vbox6;

	private global::Gtk.Table table2;

	private global::Gtk.Entry filterEntry;

	private global::Gtk.Label FindPackagesLabel;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TreeView tree;

	private global::Gtk.VBox vbox2;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Frame frame1;

	private global::Gtk.Alignment GtkAlignment;

	private global::Gtk.HBox hbox3;

	private global::Gtk.EventBox eventbox1;

	private global::Gtk.Image image1;

	private global::Gtk.Table table1;

	private global::Gtk.Label DescriptionLabel;

	private global::Gtk.Label descriptionLabelText;

	private global::Gtk.Label InstallDateLabel;

	private global::Gtk.Label installDateLabelText;

	private global::Gtk.Label nameLabel;

	private global::Gtk.Label nameLabelText;

	private global::Gtk.Label PackagerLabel;

	private global::Gtk.Label packagerLabelText;

	private global::Gtk.Label URLLabel;

	private global::Gtk.Label urlLabelText;

	private global::Gtk.Label VersionLabel;

	private global::Gtk.Label versionLabelText;

	private global::Gtk.Label GtkLabel4;

	private global::Gtk.VBox vbox4;

	private global::Gtk.Label label1;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView textview1;

	private global::Gtk.Statusbar statusbar1;

	private global::Gtk.ProgressBar progressbar2;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
		w1.Add (this.HelpAction, null);
		this.quitAction = new global::Gtk.Action ("quitAction", global::Mono.Unix.Catalog.GetString ("_Quit"), null, "gtk-quit");
		this.quitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Quit");
		w1.Add (this.quitAction, null);
		this.aboutAction = new global::Gtk.Action ("aboutAction", global::Mono.Unix.Catalog.GetString ("About"), null, "gtk-about");
		this.aboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
		w1.Add (this.aboutAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("pacinfo");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='quitAction' action='quitAction'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='aboutAction' action='aboutAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.hpaned1 = new global::Gtk.HPaned ();
		this.hpaned1.CanFocus = true;
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 218;
		this.hpaned1.BorderWidth = ((uint)(5));
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.table2 = new global::Gtk.Table (((uint)(2)), ((uint)(1)), false);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		// Container child table2.Gtk.Table+TableChild
		this.filterEntry = new global::Gtk.Entry ();
		this.filterEntry.CanFocus = true;
		this.filterEntry.Name = "filterEntry";
		this.filterEntry.IsEditable = true;
		this.filterEntry.InvisibleChar = '•';
		this.table2.Add (this.filterEntry);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table2[this.filterEntry]));
		w3.TopAttach = ((uint)(1));
		w3.BottomAttach = ((uint)(2));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.FindPackagesLabel = new global::Gtk.Label ();
		this.FindPackagesLabel.Name = "FindPackagesLabel";
		this.FindPackagesLabel.Xalign = 0f;
		this.FindPackagesLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Find Package:");
		this.table2.Add (this.FindPackagesLabel);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table2[this.FindPackagesLabel]));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox6.Add (this.table2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.table2]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.tree = new global::Gtk.TreeView ();
		this.tree.CanFocus = true;
		this.tree.Name = "tree";
		this.GtkScrolledWindow1.Add (this.tree);
		this.vbox6.Add (this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.GtkScrolledWindow1]));
		w7.Position = 1;
		this.hpaned1.Add (this.vbox6);
		global::Gtk.Paned.PanedChild w8 = ((global::Gtk.Paned.PanedChild)(this.hpaned1[this.vbox6]));
		w8.Resize = false;
		w8.Shrink = false;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.frame1 = new global::Gtk.Frame ();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0f, 0f, 1f, 1f);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.eventbox1 = new global::Gtk.EventBox ();
		this.eventbox1.Name = "eventbox1";
		// Container child eventbox1.Gtk.Container+ContainerChild
		this.image1 = new global::Gtk.Image ();
		this.image1.Name = "image1";
		this.eventbox1.Add (this.image1);
		this.hbox3.Add (this.eventbox1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.eventbox1]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table (((uint)(6)), ((uint)(2)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.DescriptionLabel = new global::Gtk.Label ();
		this.DescriptionLabel.Name = "DescriptionLabel";
		this.DescriptionLabel.Xalign = 0f;
		this.DescriptionLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Description:");
		this.table1.Add (this.DescriptionLabel);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1[this.DescriptionLabel]));
		w11.TopAttach = ((uint)(1));
		w11.BottomAttach = ((uint)(2));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.descriptionLabelText = new global::Gtk.Label ();
		this.descriptionLabelText.Name = "descriptionLabelText";
		this.descriptionLabelText.Xalign = 0f;
		this.table1.Add (this.descriptionLabelText);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1[this.descriptionLabelText]));
		w12.TopAttach = ((uint)(1));
		w12.BottomAttach = ((uint)(2));
		w12.LeftAttach = ((uint)(1));
		w12.RightAttach = ((uint)(2));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.InstallDateLabel = new global::Gtk.Label ();
		this.InstallDateLabel.Name = "InstallDateLabel";
		this.InstallDateLabel.Xalign = 0f;
		this.InstallDateLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Install Date:");
		this.table1.Add (this.InstallDateLabel);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1[this.InstallDateLabel]));
		w13.TopAttach = ((uint)(5));
		w13.BottomAttach = ((uint)(6));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.installDateLabelText = new global::Gtk.Label ();
		this.installDateLabelText.Name = "installDateLabelText";
		this.installDateLabelText.Xalign = 0f;
		this.table1.Add (this.installDateLabelText);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1[this.installDateLabelText]));
		w14.TopAttach = ((uint)(5));
		w14.BottomAttach = ((uint)(6));
		w14.LeftAttach = ((uint)(1));
		w14.RightAttach = ((uint)(2));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.nameLabel = new global::Gtk.Label ();
		this.nameLabel.Name = "nameLabel";
		this.nameLabel.Xalign = 0f;
		this.nameLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Name:");
		this.table1.Add (this.nameLabel);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1[this.nameLabel]));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.nameLabelText = new global::Gtk.Label ();
		this.nameLabelText.Name = "nameLabelText";
		this.nameLabelText.Xalign = 0f;
		this.table1.Add (this.nameLabelText);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1[this.nameLabelText]));
		w16.LeftAttach = ((uint)(1));
		w16.RightAttach = ((uint)(2));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.PackagerLabel = new global::Gtk.Label ();
		this.PackagerLabel.Name = "PackagerLabel";
		this.PackagerLabel.Xalign = 0f;
		this.PackagerLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Packager:");
		this.table1.Add (this.PackagerLabel);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1[this.PackagerLabel]));
		w17.TopAttach = ((uint)(4));
		w17.BottomAttach = ((uint)(5));
		w17.XOptions = ((global::Gtk.AttachOptions)(4));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.packagerLabelText = new global::Gtk.Label ();
		this.packagerLabelText.Name = "packagerLabelText";
		this.packagerLabelText.Xalign = 0f;
		this.table1.Add (this.packagerLabelText);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1[this.packagerLabelText]));
		w18.TopAttach = ((uint)(4));
		w18.BottomAttach = ((uint)(5));
		w18.LeftAttach = ((uint)(1));
		w18.RightAttach = ((uint)(2));
		w18.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.URLLabel = new global::Gtk.Label ();
		this.URLLabel.Name = "URLLabel";
		this.URLLabel.Xalign = 0f;
		this.URLLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("URL:");
		this.table1.Add (this.URLLabel);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1[this.URLLabel]));
		w19.TopAttach = ((uint)(3));
		w19.BottomAttach = ((uint)(4));
		w19.XOptions = ((global::Gtk.AttachOptions)(4));
		w19.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.urlLabelText = new global::Gtk.Label ();
		this.urlLabelText.Name = "urlLabelText";
		this.urlLabelText.Xalign = 0f;
		this.table1.Add (this.urlLabelText);
		global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1[this.urlLabelText]));
		w20.TopAttach = ((uint)(3));
		w20.BottomAttach = ((uint)(4));
		w20.LeftAttach = ((uint)(1));
		w20.RightAttach = ((uint)(2));
		w20.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.VersionLabel = new global::Gtk.Label ();
		this.VersionLabel.Name = "VersionLabel";
		this.VersionLabel.Xalign = 0f;
		this.VersionLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Version:");
		this.table1.Add (this.VersionLabel);
		global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table1[this.VersionLabel]));
		w21.TopAttach = ((uint)(2));
		w21.BottomAttach = ((uint)(3));
		w21.XOptions = ((global::Gtk.AttachOptions)(4));
		w21.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.versionLabelText = new global::Gtk.Label ();
		this.versionLabelText.Name = "versionLabelText";
		this.versionLabelText.Xalign = 0f;
		this.table1.Add (this.versionLabelText);
		global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table1[this.versionLabelText]));
		w22.TopAttach = ((uint)(2));
		w22.BottomAttach = ((uint)(3));
		w22.LeftAttach = ((uint)(1));
		w22.RightAttach = ((uint)(2));
		w22.YOptions = ((global::Gtk.AttachOptions)(4));
		this.hbox3.Add (this.table1);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.table1]));
		w23.Position = 1;
		w23.Expand = false;
		w23.Fill = false;
		this.GtkAlignment.Add (this.hbox3);
		this.frame1.Add (this.GtkAlignment);
		this.GtkLabel4 = new global::Gtk.Label ();
		this.GtkLabel4.Name = "GtkLabel4";
		this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Package information</b>");
		this.GtkLabel4.UseMarkup = true;
		this.frame1.LabelWidget = this.GtkLabel4;
		this.hbox2.Add (this.frame1);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.frame1]));
		w26.Position = 0;
		w26.Expand = false;
		w26.Fill = false;
		this.vbox2.Add (this.hbox2);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox2]));
		w27.Position = 0;
		w27.Expand = false;
		w27.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.Xalign = 0f;
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Package contents</b>");
		this.label1.UseMarkup = true;
		this.vbox4.Add (this.label1);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.label1]));
		w28.Position = 0;
		w28.Expand = false;
		w28.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textview1 = new global::Gtk.TextView ();
		this.textview1.CanFocus = true;
		this.textview1.Name = "textview1";
		this.textview1.Editable = false;
		this.textview1.AcceptsTab = false;
		this.GtkScrolledWindow.Add (this.textview1);
		this.vbox4.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.GtkScrolledWindow]));
		w30.Position = 1;
		this.vbox2.Add (this.vbox4);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vbox4]));
		w31.Position = 1;
		this.hpaned1.Add (this.vbox2);
		this.hbox1.Add (this.hpaned1);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.hpaned1]));
		w33.Position = 0;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w34.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar ();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		// Container child statusbar1.Gtk.Box+BoxChild
		this.progressbar2 = new global::Gtk.ProgressBar ();
		this.progressbar2.Name = "progressbar2";
		this.progressbar2.Text = global::Mono.Unix.Catalog.GetString ("Reading information...");
		this.progressbar2.Fraction = 0.19;
		this.progressbar2.PulseStep = 0.2;
		this.statusbar1.Add (this.progressbar2);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.statusbar1[this.progressbar2]));
		w35.Position = 1;
		this.vbox1.Add (this.statusbar1);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.statusbar1]));
		w36.Position = 2;
		w36.Expand = false;
		w36.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 767;
		this.DefaultHeight = 626;
		this.progressbar2.Hide ();
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.quitAction.Activated += new global::System.EventHandler (this.OnQuitActionActivated);
		this.aboutAction.Activated += new global::System.EventHandler (this.OnAboutActionActivated);
		this.filterEntry.Changed += new global::System.EventHandler (this.OnFilterEntryChanged);
		this.tree.CursorChanged += new global::System.EventHandler (this.OnTreeCursorChanged);
		this.eventbox1.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnEventbox1ButtonPressEvent);
	}
}
