
// This file has been generated by the GUI designer. Do not modify.
namespace pacinfo
{
	public partial class ImageWindow
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.EventBox eventbox1;

		private global::Gtk.Image image2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget pacinfo.ImageWindow
			this.Name = "pacinfo.ImageWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("ImageWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(2));
			this.DestroyWithParent = true;
			this.Gravity = ((global::Gdk.Gravity)(5));
			// Container child pacinfo.ImageWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.eventbox1 = new global::Gtk.EventBox ();
			this.eventbox1.Name = "eventbox1";
			// Container child eventbox1.Gtk.Container+ContainerChild
			this.image2 = new global::Gtk.Image ();
			this.image2.Name = "image2";
			this.eventbox1.Add (this.image2);
			this.vbox1.Add (this.eventbox1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.eventbox1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 70;
			this.DefaultHeight = 76;
			this.Show ();
			this.eventbox1.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnEventbox1ButtonPressEvent);
		}
	}
}
